export const PREVIEW_URL_START = "PREVIEW_URL_START";
export const PREVIEW_URL_SUCCESS = 'PREVIEW_URL_SUCCESS';
export const PREVIEW_URL_FAIL = 'PREVIEW_URL_FAIL';

export const FETCH_URL_START = "FETCH_URL_START";
export const FETCH_URL_SUCCESS = "FETCH_URL_SUCCESS"; 
export const FETCH_URL_FAIL = "FETCH_URL_FAIL"; 

